apiVersion: v1
kind: PersistentVolume
metadata:
  name: sql-pv
  namespace: mshaikh-tawazun
  labels:
    app: deploy
    name: MohammedShaikh
    type: amazonEBS
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
    volumeID: vol-06976d3f451e42135
    fsType: ext4