apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: deploy
    name: MohammedShaikh
    type: amazonEBS
  name: sql-pv-claim
  namespace: mshaikh-tawazun
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
  selector:
    matchLabels:
      type: "amazonEBS"