apiVersion: v1
kind: ResourceQuota
metadata:
  name: mshaikh-resource-quota
  namespace: mshaikh-tawazun
  labels: 
    name: MohammedShaikh
spec:
  hard:
    requests.cpu: 1
    requests.memory: 1G
    limits.cpu: 1
    limits.memory: 1G