apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: deploy
    name: Mohammed Shaikh
    namespace: mshaikh-tawazun
    type: amazonEBS
  name: sql-pv-claim
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
  selector:
    matchLabels:
      type: "amazonEBS"