apiVersion: v1
kind: ResourceQuota
metadata:
  name: mshaikh-resource-quota
  namespace: mshaikh-tawazun
  labels: 
    name: MohammedShaikh
spec:
 hard:
   requests.cpu: "2"
   requests.memory: 2Gi
   limits.cpu: "4"
   limits.memory: 4Gi